



prostaff.mail.admin-email=dubeyh@rknec.edu
prostaff.mail.from-email=onboarding@resend.dev
prostaff.mail.from-name=Prostaff Solution
resend.api.key= ${RESEND_API_KEY}

prostaff.cors.allowed-origins=https://prostafff.netlify.app

logging.level.com.prostaff=INFO