

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

prostaff.mail.admin-email=info@prostafffsolution.com
prostaff.mail.from-email=${MAIL_USERNAME}
prostaff.mail.from-name=Prostaff Solution

prostaff.cors.allowed-origins=https://prostafff.netlify.app

logging.level.com.prostaff=INFO